### ISSUE TITLE
The filter for colour, should search for the closest avaliable if the exact colour isn't avaliable

### ISSUE THREAD

**Issue by Ember-Ember** [itsthejoker/filamentcolors.xyz#20]

**Comment by itsthejoker** [comment]
Hi there, @MagentaPuppy! I'm not sure I fully understand what you're asking for; are you talking about the filter text box at the top of the page? That just applies some basic text filtering on the swatches that are on the page -- no heavy lifting there.

At the moment, I don't provide a way to search for specific hex colors because the hex colors I have aren't actually real. They're what my specific photography setup sees when looking at a plastic, and it's done that way so that colors can be computed relative to each other.

For example, if you have a specific orange, it will look different depending on what light you view it in. Because your monitor will show it differently than mine, I use what the camera gives to be able to say that "this specific orange" will look good with "this specific blue" in any light. That way, once you have the two filaments in your hand, they will still look good together -- even if they aren't the exact shades you imagined. Digital color is unyielding, so searching by hex color just won't return the actual physical colors you're hoping for (which is a disappointment for everybody). If you have a specific color you're looking for, I can give you the plastic I have that's closest but it probably won't look exactly the same once you get it into your hand.

**Comment by Ember-Ember** [comment]
I don't know what I was talking about six months ago, sorry for wasting your time
